import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/header/Header';
import { Antonio } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';

export const antonio = Antonio({
  subsets: ['latin'],
  variable: '--font-title',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${antonio.variable} antialiased`}>
        <header>
          <Header />
        </header>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
